/**
 * Re-download the vendored fonts and rewrite the @font-face block in
 * app/globals.css.
 *
 * The build must not touch the network, so this is the only thing that does,
 * and it is run by hand. See app/fonts/README.md for what is vendored and why.
 *
 *   npm run fonts
 */
import { writeFile, readFile, readdir, unlink } from 'node:fs/promises'
import path from 'node:path'

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const FONT_DIR = 'app/fonts'
const CSS = 'app/globals.css'

/**
 * Only the weights the markup asks for. Adding one here means adding it to the
 * table in app/fonts/README.md too — the point of keeping this short is that a
 * reader can tell at a glance what ships.
 */
const SPECS = [
  { family: 'Spectral', q: 'Spectral:ital,wght@0,400', subsets: ['latin', 'latin-ext'], base: 'spectral-400', weight: '400', style: 'normal' },
  { family: 'Spectral', q: 'Spectral:ital,wght@0,600', subsets: ['latin', 'latin-ext'], base: 'spectral-600', weight: '600', style: 'normal' },
  { family: 'Spectral', q: 'Spectral:ital,wght@1,400', subsets: ['latin', 'latin-ext'], base: 'spectral-400-italic', weight: '400', style: 'italic' },
  { family: 'Fraunces', q: 'Fraunces:wght@400..700', subsets: ['latin', 'latin-ext'], base: 'fraunces-var', weight: '400 700', style: 'normal' },
  // Latin only, deliberately. Display italic is used in exactly one place —
  // the ending types — and END_TYPES is a closed vocabulary of six ASCII
  // words, so the latin-ext companion would be 40KB nothing could ever
  // request. If an ending type ever needs a diacritic, add it here.
  { family: 'Fraunces', q: 'Fraunces:ital,wght@1,400..700', subsets: ['latin'], base: 'fraunces-var-italic', weight: '400 700', style: 'italic' },
  { family: 'IBM Plex Mono', q: 'IBM+Plex+Mono:wght@400', subsets: ['latin', 'latin-ext'], base: 'plexmono-400', weight: '400', style: 'normal' },
  { family: 'Amiri', q: 'Amiri:wght@400', subsets: ['arabic'], base: 'amiri-400', weight: '400', style: 'normal' },
]

const BANNER = `/* ---------------------------------------------------------------------------
   Fonts, vendored.

   These were fetched from Google Fonts at build time until a runner could not
   reach fonts.googleapis.com and the deploy failed with ETIMEDOUT. A static
   site that must be rebuilt to publish a typo fix should not depend on a third
   party being reachable at that moment, so the files now live in the repo and
   the build touches the network for nothing.

   Only the weights the site actually uses are here: 400 and 600. Fraunces
   ships as variable files covering 400-700, roman and italic. Latin faces
   carry latin and latin-ext, which is what puts the macron in Ardashīr in the
   same face as the rest of the word; Amiri carries arabic only, since it is
   here to set the script names and nothing else.

   The unicode-range on each rule is Google's own, kept verbatim. It is what
   lets the browser skip downloading latin-ext for a page with no diacritics,
   and it is the reason these are hand-written rather than declared through
   next/font/local, which has no way to express a per-file range.

   All four families are SIL Open Font License 1.1. See app/fonts/README.md.
   Regenerate with: npm run fonts

   GENERATED by scripts/fetch-fonts.mjs. Edit that, not this.
--------------------------------------------------------------------------- */`

const END = '/* --- end generated font faces --- */'

async function get(url, asText = true) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return asText ? res.text() : Buffer.from(await res.arrayBuffer())
}

const faces = []
for (const spec of SPECS) {
  const sheet = await get(
    `https://fonts.googleapis.com/css2?family=${spec.q}&display=swap`,
  )
  const blocks = [...sheet.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g)]
  for (const subset of spec.subsets) {
    const block = blocks.find((b) => b[1] === subset)
    if (!block) throw new Error(`${spec.family}: Google no longer serves subset "${subset}"`)
    const url = block[2].match(/url\((https:\/\/[^)]+\.woff2)\)/)[1]
    const range = block[2].match(/unicode-range:\s*([^;]+);/)[1].trim()
    const file = `${spec.base}-${subset}.woff2`
    const bytes = await get(url, false)
    await writeFile(path.join(FONT_DIR, file), bytes)
    faces.push({ ...spec, file, range, bytes: bytes.length })
    console.log(`${file.padEnd(38)} ${bytes.length.toLocaleString().padStart(9)} B`)
  }
}

// Anything left over from a previous run is a file nothing references.
const kept = new Set(faces.map((f) => f.file))
for (const f of await readdir(FONT_DIR)) {
  if (f.endsWith('.woff2') && !kept.has(f)) {
    await unlink(path.join(FONT_DIR, f))
    console.log(`removed stale ${f}`)
  }
}

const rules = faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')

const block = `${BANNER}\n\n${rules}\n\n${END}\n`
const css = await readFile(CSS, 'utf8')
const marker = css.indexOf(END)
const rest = marker === -1 ? css : css.slice(marker + END.length).replace(/^\n+/, '')
await writeFile(CSS, `${block}\n${rest}`)

const total = faces.reduce((n, f) => n + f.bytes, 0)
console.log(`\n${faces.length} files, ${total.toLocaleString()} bytes. globals.css rewritten.`)
