/**
 * Emit content/VERIFICATION.md: every figure in the repository, grouped by the
 * source it claims to come from, as a checklist.
 *
 * Run with: npm run verify
 *
 * The hard rules stop invented citations and invented numbers from entering.
 * They cannot check that a real citation was read correctly — that a figure
 * attributed to Taagepera is the figure Taagepera actually printed. Only the
 * author with the book open can do that, and this file is the worklist for it,
 * generated so it cannot drift from the content.
 */

import fs from 'node:fs'
import path from 'node:path'
import { parse } from 'yaml'

const C = path.join(process.cwd(), 'content')
const read = (f) => parse(fs.readFileSync(path.join(C, f), 'utf8'))

const sources = new Map(read('sources.yaml').sources.map((s) => [s.id, s]))
const refs = read('reference-set.yaml')
const claims = []

const add = (source, where, what) => {
  if (source) claims.push({ source, where, what })
}

for (const dir of fs.readdirSync(path.join(C, 'polities')).sort()) {
  const p = parse(fs.readFileSync(path.join(C, 'polities', dir, 'polity.yaml'), 'utf8'))
  const w = `polity/${p.id}`
  add(p.span.start.source, w, `span starts ${p.span.start.min}`)
  if (p.span.start.max_source) add(p.span.start.max_source, w, `span start upper bound ${p.span.start.max}`)
  add(p.span.end.source, w, `span ends ${p.span.end.min}`)
  if (p.span.end.max_source) add(p.span.end.max_source, w, `span end upper bound ${p.span.end.max}`)
  for (const c of p.capitals ?? []) add(c.source, w, `capital ${c.name}${c.from ? ` from ${c.from}` : ''}`)
  for (const [k, r] of Object.entries(p.rulers ?? {})) {
    if (r) add(r.source, w, `${k} ${r.name}${r.reign ? ` r. ${r.reign.join('-')}` : ''}`)
  }
  if (p.measures.reach_km2) {
    add(p.measures.reach_km2.source, w, `reach ${p.measures.reach_km2.value.toLocaleString('en-GB')} km2 at ${p.measures.reach_km2.at}`)
  }
  if (p.measures.peak_population) {
    add(p.measures.peak_population.source, w, `peak population ${p.measures.peak_population.value.toLocaleString('en-GB')}`)
  }
  for (const [k, c] of Object.entries(p.measures.influence ?? {})) {
    if (c.count !== null) add(c.source, w, `${k} = ${c.count}${c.items.length ? ` (${c.items.join(', ')})` : ''}`)
  }
  if (p.ended) add(p.ended.source, w, `ended by ${p.ended.type}${p.ended.year ? ` in ${p.ended.year}` : ''}`)

  for (const f of fs.readdirSync(path.join(C, 'polities', dir)).filter((f) => f.endsWith('.mdx')).sort()) {
    const raw = fs.readFileSync(path.join(C, 'polities', dir, f), 'utf8')
    const fm = /^---\n([\s\S]*?)\n---/.exec(raw)
    const meta = fm ? parse(fm[1]) : {}
    add(meta.drafted_from, `chapter/${p.id}/${f}`, `prose: "${meta.title}"`)
  }
}

for (const r of refs.polities) {
  if (r.reach_km2) add(r.reach_km2.source, `reference/${r.id}`, `reach ${r.reach_km2.value.toLocaleString('en-GB')} km2 at ${r.reach_km2.at}`)
  if (r.peak_population) add(r.peak_population.source, `reference/${r.id}`, `peak population ${r.peak_population.value.toLocaleString('en-GB')}`)
}
for (const d of refs.world_denominators) {
  if (d.world_population) add(d.world_population.source, `denominator/${d.year}`, `world population ${d.world_population.value.toLocaleString('en-GB')}`)
  if (d.world_land_under_state_control_km2) {
    add(d.world_land_under_state_control_km2.source, `denominator/${d.year}`, 'world land under state control')
  }
}
for (const e of read('edges.yaml').edges) {
  add(e.source, `edge/${e.from}->${e.to}`, `${e.type}${e.year ? ` in ${e.year}` : ''}`)
}

const bySource = new Map()
for (const c of claims) {
  if (!bySource.has(c.source)) bySource.set(c.source, [])
  bySource.get(c.source).push(c)
}

const lines = [
  '# Verification worklist',
  '',
  '<!-- Generated by scripts/verification-report.mjs. Run `npm run verify` after',
  '     changing content. Do not edit by hand; tick the boxes and commit. -->',
  '',
  'The build enforces that every citation resolves to a real work in',
  '`sources.yaml` and that no figure is invented on the spot. It cannot enforce',
  'that a real citation was read *correctly* — that the number attributed to',
  'Taagepera is the number Taagepera printed, on the page where he printed it.',
  'Only the author, with the book open, can establish that.',
  '',
  'This file is that worklist, grouped by source so one sitting with one book',
  'clears one section. Everything below is **unverified until ticked.**',
  '',
  `**${claims.length} claims across ${bySource.size} sources.**`,
  '',
  '## Where to start',
  '',
  'Sections are ordered by how much rests on the work, so the top of this file',
  'is where an hour buys the most. Sections marked **sole source** are the ones',
  'to do first: every claim on those polities resolves to that one book, so an',
  'error in reading it is an error across the whole page with nothing else in',
  'the corpus to contradict it. Where two works cover the same polity, a',
  'misreading has a chance of showing up as a disagreement. Here it does not.',
  '',
]

// Which polities depend on exactly one work. Computed here rather than read
// from the site so the worklist stands alone as a file.
// `where` is "polity/<id>" or "chapter/<id>/<slug>"; edges, reference entries
// and denominators are not per-polity and are skipped. Splitting on the first
// segment instead of the second once counted every polity claim under the
// literal string "polity", which found one sole-source work instead of ten.
const sourcesPerPolity = new Map()
for (const c of claims) {
  const [kind, id] = c.where.split('/')
  if (kind !== 'polity' && kind !== 'chapter') continue
  if (!id) continue
  if (!sourcesPerPolity.has(id)) sourcesPerPolity.set(id, new Set())
  sourcesPerPolity.get(id).add(c.source)
}
const soleFor = new Map()
for (const [polity, ids] of sourcesPerPolity) {
  if (ids.size !== 1) continue
  const only = [...ids][0]
  soleFor.set(only, [...(soleFor.get(only) ?? []), polity])
}

for (const [id, items] of [...bySource.entries()].sort((a, b) => b[1].length - a[1].length)) {
  const s = sources.get(id)
  lines.push(`## ${s?.author ? `${s.author}, ` : ''}${s?.title ?? id}`)
  if (s?.container) lines.push(`*In ${s.container}.*`)
  if (s?.url) lines.push(`<${s.url}>`)
  lines.push('', `\`${id}\` — ${items.length} claims`, '')
  const sole = soleFor.get(id)
  if (sole?.length) {
    lines.push(
      `**Sole source** for ${sole.sort().map((p) => `\`${p}\``).join(', ')} — ` +
        'nothing else in the corpus can contradict a misreading here.',
      '',
    )
  }
  for (const c of items.sort((a, b) => a.where.localeCompare(b.where))) {
    lines.push(`- [ ] \`${c.where}\` — ${c.what}`)
  }
  lines.push('')
}

fs.writeFileSync(path.join(C, 'VERIFICATION.md'), lines.join('\n'))
console.log(`content/VERIFICATION.md: ${claims.length} claims across ${bySource.size} sources`)
